apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-operator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: postgres-operator
spec:
  type: "ClusterIP"
  ports:
    - name: apiserver
      port: 8443
      protocol: TCP
      targetPort: 8443
      nodePort: 0
  selector:
    name: postgres-operator
    release: {{ .Release.Name }}
