---
title: "Upgrading to v2.6"
date: 2018-04-23T14:50:43-07:00
draft: true
---

v2.6, {docdate}

For a full list of additions and revisions that occurred in the
PostgreSQL Operator v2.5 release, please view the related release
page link:https://github.com/CrunchyData/postgres-operator/releases/tag/2.6[here].

== Required Updates

This section notes some required steps that will need to be taken
in the process of upgrading from v2.5 to v2.6.

=== Configuration File

One update in v2.6 changed the pgo.yaml file through removing the Debug flag.
The pgo.debug variable can now be removed from the pgo.yaml file as a
result. The debug flag is now called CRUNCHY_DEBUG and is set in the
deployment.json file as a default environment variable.

=== Container Resources

Release 2.6 added the concept of container resource configurations
to the pgo.yaml file. In order to specify the optional container
resource configurations, add a section as follows to your pgo.yaml
file -
....
DefaultContainerResource: small
ContainerResources:
 small:
   RequestsMemory:  2Gi
   RequestsCPU:  0.5
   LimitsMemory:  2Gi
   LimitsCPU:  1.0
 large:
   RequestsMemory:  8Gi
   RequestsCPU:  2.0
   LimitsMemory:  12Gi
   LimitsCPU:  4.0
....

WARNING: If these settings are set incorrectly or if the Kubernetes cluster
cannot meet the defined memory and CPU requirements, deployments will go into
a *pending* state.

=== Kube RBAC

Release 2.6 added a rbac.yaml file to capture the Kube RBAC
rules. These RBAC rules allow the *apiserver* and *postgres-operator*
containers access to the Kubernetes resources required for
the operator to work. As part of the deployment process, it is necessary to
execute the rbac.yaml file to set the roles and bindings required by the
operator. Adjust this file to suit local security requirements.

=== Application RBAC

Release 2.6 added an RBAC capability to secure the *pgo* application.
The *pgouser* now has a role appended at the end of of each user definition
as follows -
....
username:password:pgoadmin
testuser:testpass:pgoadmin
readonlyuser:testpass:pgoreader
....

These are defined in the following file -
....
$COROOT/conf/apiserver/pgouser
....

To match the behavior of the pre 2.6 releases, the *pgadmin* role
is set on the previous user definitions, but a *readonlyuser* is
now defined to test other role definitions. The roles are defined in
a new file called *pgorole*. This file defines each role and the
permissions for that role. By default, two roles are defined as samples -
....
pgoadmin
pgoreader
....

Adjust these default settings to meet local security requirements.

The format of this file is as follows -
....
rolename: permissionA, permissionB
....

These are defined in the following file -
....
$COROOT/conf/apiserver/pgorole
....

The complete set of permissions is documented in the link:/operator-configuration/configuration/[configuration document].

=== User Creation

Release 2.6 replaced the pgo user --add command with the pgo create user
command to improve consistency across command usage. Any scripts written
using the older style of command require an update to use the new command
syntax.

=== Replica CRD

There is a new Kubernetes Custom Resource Definition that serves the purpose
of holding replica information, called *pgreplicas*. This CRD is populated
with the pgo scale command and is used to hold per-replica specific information
such as the resource and storage configurations requested at run time.
