---
title: "Upgrading to v2.5"
date: 2018-04-23T14:50:40-07:00
draft: true
---

v2.6, {docdate}

For a full list of additions and revisions that occurred in the
PostgreSQL Operator v2.5 release, please view the related release
page link:https://github.com/CrunchyData/postgres-operator/releases/tag/2.5[here].

== Required Updates

This section notes some required steps that will need to be taken
in the process of upgrading from v2.4 to v2.5.

=== Configuration File

It will be necessary to update your existing pgo.yaml configuration
file where the Storage Configuration sections are concerned. The updated
file for v2.5 can be found
link:https://github.com/CrunchyData/postgres-operator/blob/2.5/conf/apiserver/pgo.yaml[here].
The file contained within the local installation of the Operator is located
by default in the following location -
....
$COROOT/conf/apiserver/pgo.yaml
....

=== Secrets

2.5 changed the names of the database credentials that are created
by default in order to be consistent with the way new database credentials
are named.

It will be necessary to run the following script to update your
existing clusters. This script will essentially copy the existing
secrets values and create new secrets with those same values but
named to the new standard. Run the script by passing in the name of
an existing cluster as a parameter.

....
$COROOT/bin/upgrade-secret.sh
....
